media: src/media
content:
  - name: posts
    label: Posts
    type: collection
    path: content/blog
    view:
      fields: [title, draft, date]
    fields:
      - { name: title, label: Title, type: string, required: true }
      - { name: description, label: Description, type: string }
      - { name: date, label: Date, type: date }
      - { name: draft, label: Draft, type: boolean }
      - { name: tags, label: Tags, type: string, list: true }
      - { name: body, label: Body, type: rich-text }
  - name: spectacles
    label: Spectacles
    type: collection
    path: src/spectacles
    view:
      fields: [titre, draft]
    fields:
      - { name: draft, label: Brouillon, type: boolean }
      - { name: titre, label: Titre, type: string, required: true }
      - { name: type, label: Type, type: string, required: true }
      - { name: slug, label: Slug, type: string, required: true }
      - { name: texte, label: Description, type: text }
      - { name: agenda, label: Agenda, type: code }
      - name: affiche
        label: Affiche
        type: image
        options:
          input: src/media
          output: media
          path: src/media
          categories: [ image ]
      - { name: youtube, label: youtube, type: string }
      - { name: soundcloud, label: soundcloud, type: string }
      - { name: contact, label: Contact, type: string }
      - { name: inerpretes, label: Interprêtes, type: text }
      - { name: body, label: Contenu, type: rich-text }
  - name: metadata
    label: Metadata
    type: file
    path: src/_data/metadata.js
    format: code
