media: src/media
content:
  - name: spectacles
    label: Spectacles
    type: collection
    path: src/spectacles
    view:
      fields: [titre, draft]
    fields:
      - { name: draft, label: Brouillon, type: boolean }
      - { name: titre, label: Titre, type: string, required: true }
      - { name: type, label: Type, type: string, required: true }
      - { name: slug, label: Slug, type: string, required: true }
      - { name: texte, label: Description, type: text }
      - name: formation
        label: Formation
        type: text
        description: "Description de la formation musicale"
      - name: interpretes
        label: Interprètes
        type: text
        description: "Liste des interprètes du spectacle"
      - name: agenda
        label: Agenda
        type: code
        description: "Dates et lieux des représentations"
        # fields:
        #   - { name: date, label: Date, type: string }
        #   - { name: lieu, label: Lieu, type: string }
      - name: affiche
        label: Affiche
        type: image
        options:
          input: src/media
          output: media
          path: src/media
          categories: [image]
      - name: youtube
        label: YouTube
        type: string
        description: "Lien d'intégration YouTube"
      - name: soundcloud
        label: SoundCloud
        type: string
        description: "Lien d'intégration SoundCloud"
      - name: contact
        label: Contact
        type: string
        description: "Email ou téléphone de contact"
      - name: body
        label: Modèle
        type: select
        options:
          values:
            - label: affiche à gauche
              value: |
                {% extends "modeles/affiche-gauche.html" %}
            - label: un autre modèle
              value: |
                {% extends "modeles/affiche-droite.html" %}
  - name: metadata
    label: Metadata
    type: file
    path: src/_data/metadata.json
    format: code
